# Generated by Django 2.2.8 on 2020-01-03 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year_of_production',
            field=models.PositiveIntegerField(blank=True, help_text='Use the following format < YYYY >.', validators=[django.core.validators.MinValueValidator(1895), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
