# Generated by Django 2.2.8 on 2020-01-03 14:40

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200103_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'movie', 'verbose_name_plural': 'movies'},
        ),
        migrations.AlterModelManagers(
            name='movie',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
