# Generated by Django 2.2.8 on 2020-01-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200103_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year_of_production',
            field=models.PositiveIntegerField(blank=True, help_text='Use the following format < YYYY >.'),
        ),
    ]
