# Generated by Django 2.2.9 on 2020-01-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20200120_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, through='movies.Role', to='movies.Actor'),
        ),
    ]
