# Generated by Django 2.2.9 on 2020-01-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20200121_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'actor', 'verbose_name_plural': 'actors'},
        ),
        migrations.AddField(
            model_name='role',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
