# Generated by Django 2.2.9 on 2020-01-30 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20200121_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
            ],
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title'], 'verbose_name': 'movie', 'verbose_name_plural': 'movies'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(help_text='Required.', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year_of_production',
            field=models.PositiveIntegerField(help_text='Required. Use the following format YYYY.', validators=[movies.models.year_validator]),
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('title', 'year_of_production')},
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(blank=True, to='movies.Director'),
        ),
    ]
