# Generated by Django 2.2.9 on 2020-01-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20200130_0908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ('last_name',), 'verbose_name': 'actor', 'verbose_name_plural': 'actors'},
        ),
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/actors'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/movies'),
        ),
    ]
