# Generated by Django 2.2.9 on 2020-02-03 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0012_auto_20200130_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actors_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
