# Generated by Django 2.2.9 on 2020-02-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_actor_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='place_of_birth',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
