# Generated by Django 2.2.9 on 2020-02-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_auto_20200207_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
