# Generated by Django 2.2.9 on 2020-02-13 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_auto_20200207_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD', null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='first_name',
            field=models.CharField(help_text='Required.', max_length=50, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='cm', null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='last_name',
            field=models.CharField(help_text='Required.', max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='movies', through='movies.Role', to='movies.Actor'),
        ),
        migrations.AlterField(
            model_name='role',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='movies.Actor'),
        ),
        migrations.AlterField(
            model_name='role',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='movies.Movie'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('movie', 'role')},
        ),
    ]
