# Generated by Django 2.2.9 on 2020-02-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_auto_20200213_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
