# Generated by Django 2.2.10 on 2020-02-16 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0017_auto_20200213_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directors_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
