# Generated by Django 2.2.10 on 2020-02-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_director_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/directors'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.Director'),
        ),
    ]
